# permissions for end users to edit privatecarequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: privatecarequest-editor-role
rules:
- apiGroups:
  - privateca.google.com
  resources:
  - privatecarequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - privateca.google.com
  resources:
  - privatecarequests/status
  verbs:
  - get
