# permissions for end users to view privatecarequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: privatecarequest-viewer-role
rules:
- apiGroups:
  - privateca.google.com
  resources:
  - privatecarequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - privateca.google.com
  resources:
  - privatecarequests/status
  verbs:
  - get
