
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - privateca.google.com
  resources:
  - privatecaissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - privateca.google.com
  resources:
  - privatecaissuers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - privateca.google.com
  resources:
  - privatecarequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - privateca.google.com
  resources:
  - privatecarequests/status
  verbs:
  - get
  - patch
  - update
